- src/SeerEditorWidgetSourceArea.cpp
- src/SeerSourceBrowserWidget.cpp
Not that common, but it is used in some projects. This enables syntax highlighting and 'source' grouping for .C files.
> added: consider .C files as C++

- debian/seer.install
Icon file names were not updated in `seer.install` after rename. This breaks the `dpkg-buildpackage` command.
> Fix icon file names in seer install

- src/build/README.cmake
In the src/build dir the instructions say `make seer`, probably left over from the time the executable was called that.
> Small correction to build instructions

- README.md
- src/CMakeLists.txt
- src/SeerEditorWidgetAssemblyAreas.cpp
- src/SeerEditorWidgetSourceAreas.cpp
- src/SeerGdbLogWidget.cpp
- src/SeerHexWidget.cpp
- src/SeerPrintpointCreateDialog.cpp
- src/SeerSeerLogWidget.cpp
- src/SeerTildeLogWidget.cpp
- replace `add_compile_definitions` (added in CMake ≥3.12) with `add_definitions` in `CMakeLists.txt`
* hat tip to: https://stackoverflow.com/a/61250302/785213
- add #ifdef's to support Qt 5.9.5 for Ubuntu 18.04 by replacing QString `.front()` and `.back()` methods with `.at(0)` and `.at(s.size() - 1)`
* hat tip to: https://github.com/pawelsalawa/sqlitestudio/commit/90ca398
- add #ifdef's to replace `QFontMetrics` `.horizontalAdvance()` method with `.width()` to support Qt 5.9.5 on Ubuntu 18.04
* hat tip to: https://github.com/Sigil-Ebook/Sigil/commit/a32f890
- closes #107
> Updates to build on Ubuntu 18.04 LTS (…)

- src/SeerEditorWidgetSource.h
- src/SeerEditorWidgetSourceAreas.cpp
- tests/helloworld/helloworld.cpp
This should fix the "hover" issue.
The variable's value now shows as a tooltip.  If the text is a class/function/datatype, the tooltip will show that info.
Note, you still need to select the correct frame first.  Otherwise, you'll see a tooltip like:
```
sometext:   "sometext" is not in context
```
Let me know if it's better.
> Fixed "show variable's value" on hover.

- src/SeerBreakpointCreateDialog.ui
- src/SeerBreakpointsBrowserWidget.cpp
- src/SeerUtl.cpp
- src/SeerUtl.h
- tests/gdbmi_condition/.gitignore
- tests/gdbmi_condition/Makefile
- tests/gdbmi_condition/gdbmi_condition.cpp
- tests/hellofibonacci/breakpoints.seer
- tests/hellofibonacci/hellofibonacci.cpp
Add the 'if' word to the dialogs.
Parse the breakpoints table more effieciently.
> Cosmetic changes for specifying conditions in breakpoints.

- src/SeerDebugDialog.cpp
- src/SeerGdbWidget.cpp
- src/resources/help/ConnectDebugMode.md
- src/resources/help/seergdb.hlp
- tests/hellogdbserver/project.seer
Some types of remote gdbserver (gdbstubs) will not load the executable. So Seer needs to do it itself. QEMU debugging is such a case. Note, simple use of Seer+gdbserver does not require this.
> Re-add executable argument for 'connect' mode.

- src/SeerMainWindow.cpp
- src/SeerRegisterValuesBrowserWidget.ui
- src/SeerThreadManagerWidget.ui
- src/resources/qdarkstyle/ABOUT.md
- src/resources/qdarkstyle/dark/darkstyle.qss
- src/resources/qdarkstyle/light/lightstyle.qss
This fixes some gui issues with QDarkStyle.   
- QTabBar has the wrong background color between the left QTabButtons and the widget on the far right.
- QDarkStyle messes up some QComboBox widgets and makes the menu entry larger than it needs to.
- The left and right Seer panels can be made smaller. Helps those who don't have large terminals.
> 226 add an internal dark and light style

- README.md
Hi @epasveer,
As we've added this package to openSUSE Tumbleweed, I think it'd be useful to have the install instructions for that particular distribution on the README.
Let me know, thank you!
> Add openSUSE Tumbleweed install instructions

- CHANGELOG.md
- src/SeerMainWindow.cpp
Fixed.
A regression. I must have deleted the call to set the new font in the EditorManager.
> Fixed setting/saving font settings.

- src/SeerStructVisualizerWidget.cpp
For simple variable types (ints, floats, etc.) there were no sub children in the tree widget view. The 'expandAll' call would fail and result in a segfault (Qt bug?).
The fix is to only call 'expandAll' if there are sub children, as in the case of structures.
> Fix bug with expanding tree if there are no children (displaying simple variable types)

- CHANGELOG.md
- src/SeerGdbWidget.cpp
- src/SeerGdbWidget.h
- src/seergdb.cpp
> 271 document adding a prettyprinter for qstring

- CHANGELOG.md
- src/SeerEditorWidgetSource.h
- src/SeerEditorWidgetSourceAreas.cpp
- src/SeerMainWindow.cpp
This is fixed. Somehow a regression happened as this worked before.
> 266 mouse hover doesnt display variable value reliably

- CHANGELOG.md
- src/SeerConsoleWidget.cpp
- src/SeerConsoleWidget.h
- src/SeerGdbWidget.cpp
- src/SeerMemoryVisualizerWidget.cpp
- tests/hellocurses/.gitignore
- tests/hellocurses/Makefile
- tests/hellocurses/helloworld.cpp
- tests/hellocurses/triangle.cpp
- tests/helloucurses/.gitignore
- tests/helloucurses/Makefile
- tests/helloucurses/breakpoints.seer
- tests/helloucurses/helloucurses.c
> 286 auto resize of output window makes this debugger unusable for my project

- CHANGELOG.md
- src/SeerConsoleWidget.cpp
- src/SeerGdbWidget.cpp
- src/SeerGdbWidget.h
- src/SeerMainWindow.cpp
- src/SeerUtl.cpp
- src/SeerUtl.h
- tests/hellogdbserver/README
Fixes all known problems when reordering message tabs.
> 292 console tab position is not saved correctly

- src/CMakeLists.txt
CMake 3.5.0 was released about 9 years ago, so compatibility with older versions is probably not an issue
closes #304
> make compatible with CMake 4.0

- src/SeerCppSourceHighlighter.cpp
I noticed that functions are not highlighted if some spaces lie between the function name and the open parenthesis.
This simple fix fixes the problem.
> allow space before parenthesis at end of functions

- src/SeerCppSourceHighlighter.cpp
Some keywords can be confused with functions (such as for ( ... )).
In such cases, these must be highlighted as keywords, not functions.
> improve hightlighting : give keywords high precedence than functions

- src/SeerDebugDialog.cpp
Core dumps on OpenBSD are named like that.
> SeerDebugDialog: offer to open '*.core' core dump files as well

- src/SeerSourceBrowserWidget.cpp
Fixed.
Opened trees for the Source Browser are no longer closed when searching.
Also, I organized the 3 trees by:  Source, Headers, Misc.
> Don't collapse items when searching.
