epasveer/seer

src/SeerBreakpointCreateDialog.cpp, src/SeerEditorWidgetSourceAreas.cpp, src/SeerPrintpointCreateDialog.cpp
Adds double quotes to source file paths to fix garbage data error.
Fixes #84
=> Allow breakpoints for files with spaces

src/SeerGdbConfigPage.ui
=> Fix typo in GDB config

src/CMakeLists.txt
this commit fixes https://github.com/epasveer/seer/issues/98
=> Fix debian and cmake build on linux

.github/workflows/ubuntu-latest.yml, src/CMakeLists.txt
I added a debian pkg build to the workflow to overcome recurring debian build issues
=> Add debian pkg workflow

CHANGELOG.md, src/CMakeLists.txt, src/SeerGdbWidget.cpp, src/SeerGdbWidget.h, src/SeerMainWindow.cpp, src/SeerMainWindow.h, src/SeerMainWindow.ui, src/SeerMessagesBrowserWidget.cpp, src/SeerMessagesBrowserWidget.h, src/SeerMessagesBrowserWidget.ui
Move gdb messages into a tab in the breakpoints view.
=> 157 ux bug or flaw seer execution messages popup is getting in the way a lot

src/CMakeLists.txt, src/build/README.cmake
Seer's cmake will now set the C++ language level.  I'll update the Wiki to include a comment as well.
=> Fix CMakeLists.txt to add C++ level (11 or 17)

src/SeerStackLocalsBrowserWidget.cpp, src/SeerStackLocalsBrowserWidget.h, src/SeerStructVisualizerWidget.cpp, tests/hellostruct/hellostruct.cpp
Nested viewing of structures in the Locals tab should be implemented now.   It's in "main", if you want to pull it and see if you like it.  Let me know.
=> Added nested struct viewing in StackLocals tab.

src/SeerStackArgumentsBrowserWidget.cpp, src/SeerStackArgumentsBrowserWidget.h, src/SeerStackArgumentsBrowserWidget.ui, src/SeerVariableTrackerBrowserWidget.cpp, src/SeerVariableTrackerBrowserWidget.h, src/SeerVariableTrackerBrowserWidget.ui, tests/hellostruct/hellostruct.cpp
Add nested struct viewing to Tracker.
=> 178 suggestion struct visualizer in locals tab

src/SeerRegisterValuesBrowserWidget.ui
It is good to see full profile name.
=> make register profile combo larger

src/SeerConfigDialog.cpp, src/SeerGdbWidget.cpp, src/SeerKeysConfigPage.cpp, src/SeerMainWindow.cpp, src/SeerUtl.cpp, src/SeerUtl.h
This fixes the 3 issues raised by issue #233.
As well, a separate bug was fixed with the handling of the Key configurations in the Config dialog.
=> 233 configuration of rr

tests/hellonim/.gitignore, tests/hellonim/Makefile, tests/hellonim/hellonim.nim, tests/hellonim/project.seer
Add a test program for the Nim language.   The wiki has been updated to show how to setup Seer for debugging Nim programs.
=> Looks like gdb supports Nim - then so does Seer!

src/CMakeLists.txt, src/QAnsiTextEdit.cpp, src/QAnsiTextEdit.h, src/SeerConsoleWidget.cpp, src/SeerConsoleWidget.h, src/SeerConsoleWidget.ui, src/SeerCppSourceHighlighter.cpp, src/SeerGdbWidget.cpp, tests/helloansicodes/.gitignore, tests/helloansicodes/ANSI-color-codes.h, tests/helloansicodes/Makefile, tests/helloansicodes/helloansicodes.c
This should fix the ANSI color codes in the Seer console, for now.
=> 240 seer console does not interpret ansi escape codes

tests/helloarrayofstructs/.gitignore, tests/helloarrayofstructs/Makefile, tests/helloarrayofstructs/README, tests/helloarrayofstructs/helloarrayofstructs.cpp, tests/helloforksegv/.gitignore, tests/helloforksegv/Makefile, tests/helloforksegv/README, tests/helloforksegv/helloforksegv.cpp
Started as changing the 2D array visualizer to 3D.  Instead, reverted that but kept some new test programs.
=> Play 3d array visualizer

CHANGELOG.md, src/CMakeLists.txt, src/SeerGdbWidget.cpp, src/SeerGdbWidget.h, src/SeerStackDumpBrowserWidget.cpp, src/SeerStackDumpBrowserWidget.h, src/SeerStackDumpBrowserWidget.ui, src/SeerStackDumpSettingsDialog.cpp, src/SeerStackDumpSettingsDialog.h, src/SeerStackDumpSettingsDialog.ui, src/SeerStackManagerWidget.cpp, src/SeerStackManagerWidget.h, src/SeerUtl.cpp, src/SeerUtl.h, src/resources/help/StackInfoBrowser.md
Finishes the implementation of the the stack viewer.
=> 249 add stack viewer

CHANGELOG.md, src/SeerGdbWidget.cpp, src/SeerGdbWidget.h
Fixed. Ignoring certain system files and directories works.
=> Fixed bug #273.

src/SeerBreakpointCreateDialog.cpp, src/SeerCatchpointCreateDialog.cpp, src/SeerCatchpointCreateDialog.ui, src/SeerPrintpointCreateDialog.cpp, src/SeerWatchpointCreateDialog.cpp, src/SeerWatchpointCreateDialog.ui
=> Set focus to first ui widget.

CHANGELOG.md, src/SeerWatchpointsBrowserWidget.cpp
=> Fixed commands with a watchpoint.

CHANGELOG.md, src/SeerGdbWidget.cpp, src/SeerGdbWidget.h, src/SeerUtl.cpp, src/SeerUtl.h
=> 288 ignore directory option does not work always for ignoring missing source files

.github/workflows/debian-bullseye.yml, .github/workflows/macos-latest.yml, src/SeerEditorWidgetAssembly.cpp, src/SeerEditorWidgetSource.cpp
=> Change to build QT6 version for Svg support.

CHANGELOG.md, src/SeerAdaExceptionsBrowserWidget.cpp, src/SeerCatchpointCreateDialog.cpp, src/SeerCatchpointCreateDialog.h, src/SeerCatchpointCreateDialog.ui, src/SeerCatchpointsBrowserWidget.cpp, src/resource.qrc, src/resources/mi-python/MICatchpoint.py
=> Add remaining catchpoint types.

tests/helloobjectivec/.gitignore, tests/helloobjectivec/Makefile, tests/helloobjectivec/hellotictactoe.m
=> Test program for ObjectiveC on Linux.

src/SeerGdbWidget.cpp
=> Reset RR direction to 'forward' on debug restart.

CHANGELOG.md, src/SeerDebugDialog.cpp, src/SeerDebugDialog.h, src/SeerDebugDialog.ui, src/SeerMainWindow.cpp, src/seergdb.cpp, tests/helloworld/project.seer, tests/helloworld/project_connect.seer
=> 343 default rr trace to latest trace location

tests/helloodin/.gitignore, tests/helloodin/Makefile, tests/helloodin/README, tests/helloodin/demo.odin, tests/helloodin/helloodin.odin
=> Some Odin test programs.
